[package]
name = "tatum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
axum = "0.6.19"
barrage = "0.2.3"
clap = { version = "4.3.19", features = ["derive"] }
dashmap = "5.5.0"
kanal = "0.1.0-pre8"
prost = "0.11.9"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.9.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }


[build-dependencies]
tonic-build = "0.9"
